---
title: "Process Summary: Registration, Publication and Dissemination of a CEE Evidence Synthesis"
format:
  html:
    toc: true
    toc-depth: 3
    number-sections: true
bibliography: refs.bib
params:
  last_updated: ""
execute:
  echo: false
---

This section provides a summary of the steps in the conduct of a CEE Evidence Synthesis (Systematic Review, Systematic Map or Rapid Review), an overview of how authors register their Evidence Synthesis with CEE, and the process of submission and peer review that ensures CEE Evidence Syntheses are conducted to high standards.

## **The CEE registration, submission and deposition process**

CEE operates an open-access policy and all contributed articles (e.g. evidence syntheses) are published (subject to peer review) in its open-access journal *Environmental Evidence* ([www.environmentalevidencejournal.org](http://www.environmentalevidencejournal.org/)). This provides authors with a high level of visibility for their publications.

Here we set out the process for registering intent to conduct and contribute a CEE Evidence Synthesis, and for publishing Protocols, Systematic Reviews and Systematic Maps and Rapid Reviews in *Environmental Evidence*. High standards of reporting are expected in the conduct of a CEE Evidence Synthesis and this starts with the registration of a Protocol and continues through to the provision of supplementary material such as data extraction spreadsheets and a list of excluded articles.  For preparation of manuscripts, including templates and checklists, go to the *Environmental Evidence* journal website at <http://environmentalevidencejournal.biomedcentral.com/submission-guidelines>

Registration and submission of an Evidence Synthesis is an interactive stepwise process as follows;

1.  Prospective protocols must be submitted for registration to *PROCEED* through its electronic submission system. For full instructions for authors on Protocol registration go to (https://www.proceedevidence.info/). This serves as an application for registration to conduct a CEE Evidence Synthesis. There is no peer review process at this stage but protocols will be checked by editors for standards of reporting and conduct and revisions may be required before acceptance in the PROCEED database. Please note that PROCEED is a free service and can be used whether authors intend to conduct a CEE Evidence Synthesis or some other form of review that may be published elsewhere.

2.  Submission of the protocol for publication in *Environmental Evidence* is optional for Systematic Reviews and Systematic Maps (see next), but not recommended for Rapid Reviews due to time constraints. If publication of a Protocol in *Environmental Evidence* is planned then registration in PROCEED can be submitted simultaneously with submission to *Environmental Evidence* and the PROCEED version held and finalised once peer review comments from the journal have been received and the protocol accepted. On submission to *Environmental Evidence* the draft Protocol will be sent out for peer review. Comments will be returned to the authors and appropriate revisions may be requested to finalise the Protocol. By publishing your Protocol in *Environmental Evidence* you are registering with CEE your intent to conduct, and submit to this journal for publication, a CEE Evidence Synthesis. You will be asked to confirm that you and your co-authors are aware of and agree with this commitment when you submit by agreeing to the following statement: ‘The authors hereby submit our Protocol for publication in *Environmental Evidence*. By doing so we register with CEE our intent to conduct and submit to this journal a full and original Systematic Review/Map Report for publication and archiving in the CEE Library’.

3.  Once conducted and written up, submission of the completed Evidence Synthesis to *Environmental Evidence* follows the same journal submission process. If acceptable after an initial screening (compliance with submission guidelines and journal format), the draft Evidence Synthesis will be sent out for peer review. Comments will be returned to the authors and appropriate revisions may be requested before acceptance.

4.  The revised and completed Evidence Synthesis (and its associated supplementary material) will be published in *Environmental Evidence* and recorded as finalised on the CEE website.

Please note that CEE does not accept manuscripts of unregistered Evidence Syntheses (i.e. those without a previously registered and/or published protocol) nor does it accept retrospective protocols or registration of already completed Evidence Syntheses. CEE reserves the right to reject protocols and Evidence Syntheses if they do not meet our standards or are otherwise inappropriate.

Article Processing Charges for publication in Environmental Evidence of both the protocol and Evidence Syntheses are payable (http://environmentalevidencejournal.biomedcentral.com/about) in line with most open-access journals. Protocol APCs include a charge for CEE support that contributes to the running of CEE as a not-for-profit organisation.

CEE operates a supportive policy for review teams undertaking Evidence Syntheses and seeks to provide help and guidance, particularly during the protocol finalisation stage (including through web-based support materials and training events) to increase the chances of Evidence Syntheses being successfully completed.

## **Supplementary materials**

The transparency of Evidence Syntheses is enhanced by the provision of a range of mandatory supplementary materials. Some can be provided as appendices whilst others may be posted as additional files on the review webpage. For a full checklist see @sec-chapt9.

## **Further dissemination of findings**

Although CEE Evidence Syntheses are designed to be reliable sources of evidence, they do not necessarily make the evidence very accessible to a non-scientific readership. After all the work of searching, screening, appraising, extracting and synthesising evidence and writing the report, it is worth considering whether the full evidence synthesis format is sufficient or appropriate for disseminating the key outcomes to your target audience. The publication of the full CEE Evidence Synthesis constitutes an important resource and a transparent audit trail of methodology but may not be suitable as a dissemination tool to reach decision makers. Other formats such as policy briefs, executive summaries and guidance notes can be developed and posted on the Evidence Synthesis webpage (as well as being disseminated elsewhere). Such documents often require some special skills in to make the conclusions and recommendations, as well as their justification, accessible to a non-scientific audience. They can be written by the review team but can also be designed by a specialist or during meetings with policy makers and/or practitioners and managers.

## **Updating an Evidence Synthesis** {#sec-update1}

Evidence syntheses can only be accurate assessments of the evidence base when they are up to date. As soon as the search is completed the reliability of an evidence synthesis as a synthesis of ‘all available evidence’ begins to decline. The rate of decline is dependent on the rate of publication of new studies and so varies from subject to subject. An outdated Systematic Review or Systematic Map may be misleading, so they should periodically be updated. Fortunately, the process of updating a CEE Evidence Synthesis should not be as burdensome as the original process, provided that accurate reporting was achieved, and good records were kept of the original process. We encourage the publication and archiving of as full a record as possible of all procedures and outcomes as supplementary materials. At the time of writing, updating a CEE Evidence Synthesis is yet to be completed; we suggest considering updating a Systematic Review or Systematic Map 3-5 years after publication depending on the rate of publication of new primary studies (See @sec-updateSearch). The process for registering an update is the same as for an original Evidence Synthesis and should begin with an updated Protocol. Updates can be proposed by original authors, other review teams or a combination and should be justified in terms of new studies potentially strengthening the evidence base or the potential to improve the synthesis in some way.
